dist: focal
sudo: required

language: go
go:
  - 1.13.4

go_import_path: github.com/alibaba/pouch

before_install:
  |
    echo $TRAVIS_COMMIT_RANGE
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)' || {
      echo "travis does not run for document-only changed"
      exit
    }

install:
  - sudo apt-get install -y net-tools libbtrfs-dev

notifications:
  webhooks:
    urls:
      - http://47.96.190.121:6789/ci_notifications
    on_failure: always
    on_error: always

jobs:
  include:
    - arch: amd64
      stage: test
      name: "Unit test"
      script: ./travis_ci.sh unittest
    - arch: arm64-graviton2
      virt: vm
      group: edge
      stage: test
      name: "Unit test"
      script: ./travis_ci.sh unittest

    - arch: amd64
      stage: test
      name: "CRIv1alpha2 test"
      script:
        - ./travis_ci.sh criv1alpha2test
    - arch: arm64-graviton2
      virt: vm
      group: edge
      stage: test
      name: "CRIv1alpha2 test"
      script:
        - ./travis_ci.sh criv1alpha2test

    - arch: amd64
      stage: test
      name: "Node e2e test"
      script:
        - ./travis_ci.sh nodee2etest
    - arch: arm64-graviton2
      virt: vm
      group: edge
      stage: test
      name: "Node e2e test"
      script:
        - ./travis_ci.sh nodee2etest

    - arch: amd64
      stage: test
      name: "Integration test 0"
      script:
        - ./travis_ci.sh integrationtest 4 0
    - arch: arm64-graviton
      virt: vm
      group: edge
      stage: test
      name: "Integration test 0"
      script:
        - ./travis_ci.sh integrationtest 4 0
    - arch: amd64
      stage: test
      name: "Integration test 1"
      script:
        - ./travis_ci.sh integrationtest 4 1
    - arch: arm64-graviton2
      virt: vm
      group: edge
      stage: test
      name: "Integration test 1"
      script:
        - ./travis_ci.sh integrationtest 4 1
    - arch: amd64
      stage: test
      name: "Integration test 2"
      script:
        - ./travis_ci.sh integrationtest 4 2
    - arch: arm64-graviton2
      virt: vm
      group: edge
      stage: test
      name: "Integration test 2"
      script:
        - ./travis_ci.sh integrationtest 4 2
    - arch: amd64
      stage: test
      name: "Integration test 3"
      script:
        - ./travis_ci.sh integrationtest 4 3
    - arch: arm64-graviton2
      virt: vm
      group: edge
      stage: test
      name: "Integration test 3"
      script:
        - ./travis_ci.sh integrationtest 4 3
